### ISSUE TITLE
关于评论问题

### ISSUE THREAD

**Issue by dyt5AAUI** [gaobinzhan/CommentPush#1]
在handsome主题下面使用，评论报错。
报错内容：评论通知
[object HTMLDivElement]

**Comment by Player626** [comment]
请留下你的网站呢，我去试试昂

**Comment by dyt5AAUI** [comment]
> 请留下你的网站呢，我去试试昂

现在已经修好了。我把插件禁用重新打开就正常了

**Comment by dyt5AAUI** [comment]
对了，那个SMTP推送什么时候上线啊。阿里云推送，这个文档能写详细的点不🙃🙃🙃🙃
