### ISSUE TITLE
关于 Server酱 推送的接口变更

### ISSUE THREAD

**Issue by anwen-anyi** [gaobinzhan/CommentPush#10]
CommentPush-master\lib\WeChatService.php  第52行 Server酱推送的接口应该改下吧? 哪个貌似是旧版的接口了,现在我记得已经没有哪个旧版的了...现在的接口是新版的了.. 我用哪个旧版的填写后无法收到推送的消息,手动换了新版接口才收到消息.

旧版,变更前   https://sc.ftqq.com/
新版,变更后   https://sctapi.ftqq.com/

或者增加一个选项使用旧版新版二选一呢...嘻嘻
邮箱 anwen_anyi@foxmail.com

**Comment by Player626** [comment]
你可以直接提`pr`啊 哈哈哈

**Comment by anwen-anyi** [comment]
我不太懂这个...


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Stitch-June/CommentPush"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 晚上6:29
***@***.***&gt;;
抄送:&nbsp;"QQ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Stitch-June/CommentPush] 关于 Server酱 推送的接口变更 (#10)





 
你可以直接提pr啊 哈哈哈
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Player626** [comment]
https://github.com/Stitch-June/CommentPush/releases/tag/1.7.4

**Comment by anwen-anyi** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 上午10:36
收件人: ***@***.***&gt;; 
抄送: "QQ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Stitch-June/CommentPush] 关于 Server酱 推送的接口变更 (#10)





 
https://github.com/Stitch-June/CommentPush/releases/tag/1.7.3
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Player626** [comment]
https://github.com/Stitch-June/CommentPush/releases/tag/1.7.4
