### ISSUE TITLE
Typecho v1.2.0-rc.1 保存报错

### ISSUE THREAD

**Issue by KurococLiu** [gaobinzhan/CommentPush#13]
报错信息：
> Argument 1 passed to Typecho\Validate::required() must be of the type string or null, array given

**Comment by Player626** [comment]
通过typecho的版本号来看 应该是做了不兼容的更新导致的

**Comment by KurococLiu** [comment]
> 通过typecho的版本号来看 应该是做了不兼容的更新导致的
大概是在更新1.2.0正式版后适配新版本还是会在最近开始呢？rc大概率跟正式版也没啥大差别了吧我觉得。

**Comment by Player626** [comment]
我今天看看吧

**Comment by Player626** [comment]
没发布正式版前 任何改动都是有可能的

**Comment by KurococLiu** [comment]
> 没发布正式版前 任何改动都是有可能的

Soga，谢谢
