### ISSUE TITLE
开启SMTP，QQ推送和微信推送失效

### ISSUE THREAD

**Issue by dyt5AAUI** [gaobinzhan/CommentPush#2]
开启SMTP，QQ推送和微信推送失效。
地址：www.whoit.top

**Comment by dyt5AAUI** [comment]
![image](https://user-images.githubusercontent.com/26762239/80854959-087eaf00-8c6f-11ea-97a2-99bc2b2d9c63.png)

**Comment by dyt5AAUI** [comment]
![image](https://user-images.githubusercontent.com/26762239/80854963-12081700-8c6f-11ea-8b4e-9c6059d9865b.png)

**Comment by Player626** [comment]
已经修复
