### ISSUE TITLE
php8测试评论时候失败

### ISSUE THREAD

**Issue by odyf** [gaobinzhan/CommentPush#8]
![QQ截图20210715152536](https://user-images.githubusercontent.com/72725679/125747012-f16d6573-5ebc-4e54-88d9-22de39af9755.png)

**Comment by odyf** [comment]
经过测试在相同网络下，把php8版本转换为php7.4版本成功发送邮件

**Comment by Player626** [comment]
https://github.com/Stitch-June/CommentPush/releases/tag/1.7.2

**Comment by Player626** [comment]
下载这个版本 我刚发的

**Comment by Player626** [comment]
可以支持php8

**Comment by odyf** [comment]
![image](https://user-images.githubusercontent.com/72725679/125752213-1fcf2697-3c9a-4899-9699-c22247810bbe.png)
老哥稳，我刚删除php8环境，有空我再调整回来

**Comment by aomsir** [comment]
牛啊牛啊
