### ISSUE TITLE
qq推送貌似失效了

### ISSUE THREAD

**Issue by FlyRenxing** [gaobinzhan/CommentPush#9]
您好，qq推送貌似失效了。使用smtp并无问题，应该不是我配置问题。
查看了下您的源码并没有找到qq推送的接口地址呀..只找到了请求方式和内容格式...请问接口地址是在哪个文件呢...有些好奇
目前官方接口是：私聊消息推送接口：https://qmsg.zendee.cn/send/您的KEY
感谢！
![图片](https://user-images.githubusercontent.com/21098184/132031027-cd0a9188-333d-430a-b1d0-4ba34e3df590.png)

**Comment by Player626** [comment]
qq推送地址 是你自己填写的

**Comment by Player626** [comment]
插件不是有个配置项嘛

**Comment by FlyRenxing** [comment]
插件里的配置项是填了的，您那边测试没问题吗？😂😂

**Comment by Player626** [comment]
![image](https://user-images.githubusercontent.com/44792981/133015317-c18e9c72-4fc2-4414-9d2b-23d74384ca26.png)

**Comment by Player626** [comment]
你是不是没有开启这个远程功能. 宝塔默认关闭的.
https://github.com/Stitch-June/CommentPush#%E4%BD%BF%E7%94%A8%E9%A1%BB%E7%9F%A5

**Comment by FlyRenxing** [comment]
![图片](https://user-images.githubusercontent.com/21098184/133032729-ae54e237-aac3-4547-a7ad-0b63157cfb6b.png)
allow_url_fopen也是开着的..Qmsg的接口确实没问题，但这个插件里对接可能有些问题，我用这个插件smtp邮件是没问题的，但qmsg始终不行...也没有找到相关日志

**Comment by FlyRenxing** [comment]
![图片](https://user-images.githubusercontent.com/21098184/133034534-e8aa8b83-a5f3-4e35-855b-79db3b771e73.png)
![图片](https://user-images.githubusercontent.com/21098184/133034595-e46ebe45-6a1e-412b-9239-11e69667e83e.png)
貌似这里的qqapiurl没有加上“https://qmsg.zendee.cn/send/”这个url
我也搜索了您这个储存库也没有发现这个api地址

**Comment by FlyRenxing** [comment]
经查，是因为没有写Qmsg的接口地址导致请求没发出去...加上请求地址即可...修改后已测试正常。提交了PR望合并。 #11

**Comment by FlyRenxing** [comment]
不好意思看错了...我以为在插件里只要填Key就行了...猛的一看发现要填完整的地址.....
